export const INGREDIENT_ADDED = "INGREDIENT_ADDED";
export const INGREDIENT_REMOVED = "INGREDIENT_REMOVED";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const INGREDIENT_INIT = "INGREDIENT_INIT";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_INIT = "PURCHASE_BURGER_INIT";
export const PURCHASE_INIT = "PURCHASE_INIT";
export const PURCHASE_BURGER = "PURCHASE_BURGER";

export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const CHECK_AUTH_STATE = "CHECK_AUTH_STATE";

export const SET_REDIRECT_PATH ="SET_REDIRECT_PATH";
